### ISSUE TITLE
Global style should be applied to all activities

### ISSUE THREAD

**Issue by Grandolf49** [The-Robotics-Forum/netra#22] opened 2020-08-29 14:26 UTC
**Summary**

Currently, for each activity, style parameter is set in Android Manifest. Instead it should be added in the `res/values/styles.xml` file

**Comment by preranashelke** [comment] 2021-01-20 18:47
I would like to do this please assign it to me

**Comment by avivijay19** [comment] 2021-01-21 05:19
The issue is already assigned to some one else please try other.

**Closed** 2021-01-21 05:21 UTC
Labels: good first issue

**Comment by preranashelke** [comment] 2021-01-21 05:29
Okay
